### ISSUE TITLE
whats is the meaning of hi✋✋

### ISSUE THREAD

**Issue by opoc-company** [opoc-reza/cooking#1]
pls some one tell me why is what in whatpls some one tell me why is what in whatpls some one tell me why is what in whatpls some one tell me why is what in whatpls some one tell me why is what in whatpls some one tell me why is what in whatpls some one tell me why is what in whatpls some one tell me why is what in whatpls some one tell me why is what in what

**Comment by opoc-reza** [comment]
what are you talking about ???

**Comment by opoc-company** [comment]
nothing by 💯 👍 👎 👍 👍 👍

**Comment by opoc-reza** [comment]
shut up
